# Generated by Django 2.0.1 on 2018-01-14 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(db_column='name', max_length=20, primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, db_column='comment', max_length=200)),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date')),
                ('amount_CNY', models.DecimalField(db_column='amount_CNY', decimal_places=2, max_digits=10)),
                ('comment', models.CharField(blank=True, db_column='comment', max_length=200)),
                ('client', models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.CASCADE, to='orders.Client')),
            ],
            options={
                'db_table': 'ClientPayment',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date')),
                ('exchange_rate', models.FloatField(blank=True, db_column='exchange_rate', null=True)),
                ('actual_deduction_CNY', models.DecimalField(blank=True, db_column='actual_deduction_CNY', decimal_places=2, max_digits=10, null=True)),
                ('comment', models.CharField(blank=True, db_column='comment', max_length=200)),
                ('client', models.ForeignKey(db_column='client', on_delete=django.db.models.deletion.CASCADE, to='orders.Client')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(db_column='item_name', max_length=200)),
                ('price_AUD', models.DecimalField(db_column='price_AUD', decimal_places=2, max_digits=10)),
                ('item_number', models.IntegerField(db_column='item_number', default=1)),
                ('comment', models.CharField(blank=True, db_column='comment', max_length=200)),
                ('order', models.ForeignKey(db_column='order', on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
    ]
